##=================================================================
## Makefile variables for compiling locally in Groningen.
## Author: T.E. Mulder => t.e.mulder@uu.nl
##=================================================================
##   Location specific variables:
##
LOCATION     = LOCAL
##   Compiler identifier flag, options are
##   GNU, G95, INTEL, ASTER, ORBIT, HOPF, PGI and HUYGENS
COMP_IDENT   = GNU
##   Trilinos version:
TRIVERSION   = 11.12
##   Trilinos directory containing lib and include dirs:
TRIDIR       = /var/tmp/trilinos/${TRIVERSION}
##   Project base directory
PROJECT_BASE = /var/tmp/emic
##   Make flags
MFLAGS       = -j 4
##=================================================================
include $(PROJECT_BASE)/make.inc/Makefile.all