language: cpp

addons:
  apt:
    packages: &linux_deps
      - git
      - build-essential
      - libopenmpi-dev
      - openmpi-bin
      - cmake-data
      - cmake
      - trilinos-all-dev
      - libx11-dev
      - x11proto-core-dev
      - libopenblas-dev
      - libhdf5-openmpi-dev
      # Manual Trilinos dependencies, which are bugged in 16.04
      - libmumps-dev
      - binutils-dev
      - libiberty-dev
      - libtbb-dev
      - libsuperlu-dev
      - libptscotch-dev
      # RAILS
      - libslicot-dev

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *linux_deps
            # Compilers
            - g++-5
            - gfortran-5
      env:
         - OMPI_CC=gcc-5 OMPI_CXX=g++-5 OMPI_FC=gfortran-5 CC=gcc-5 CXX=g++-5 FC=gfortran-5

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *linux_deps
            # Compilers
            - g++-8
            - gfortran-8
      env:
         - OMPI_CC=gcc-8 OMPI_CXX=g++-8 OMPI_FC=gfortran-8 CC=gcc-8 CXX=g++-8 FC=gfortran-8

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - *linux_deps
            # Compilers
            - clang
            - gfortran
      env:
         - OMPI_CC=clang OMPI_CXX=clang++ OMPI_FC=gfortran CC=clang CXX=clang++ FC=gfortran

    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          taps: nlesc/nlesc
          packages:
            - ccache
          update: true
      env:
         - CMAKE_PREFIX_PATH=/usr/local/opt/trilinos/
      before_cache:
         - brew cleanup
      before_install:
         - brew uninstall netcdf hdf5 gdal postgis
         - brew install nlesc/nlesc/trilinos

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  # Install RAILS
  - git clone https://github.com/Sbte/RAILS.git
  - cd RAILS
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - make install
  - cd ../..

install:
  # Install JDQZPP
  - git clone https://github.com/erik808/jdqzpp.git
  - cd jdqzpp
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - make install
  - cd ../..
  # Build I-EMIC
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - make

script:
  - make check
