##=================================================================
## Makefile variables for compiling locally in Groningen.
## Author: T.E. Mulder => t.e.mulder@uu.nl
##=================================================================
##   Location specific variables:
##
LOCATION     = LOCAL
##   Compiler identifier flag, options are
##   GNU, G95, INTEL, ASTER, ORBIT, HOPF, PGI and HUYGENS
COMP_IDENT   = GNU
##   Trilinos version:
TRIVERSION   = 11.12
##   Trilinos directory containing lib and include dirs:
TRIDIR       = /var/tmp/trilinos/${TRIVERSION}
##   MRILU directory containing lib and mod subfolders
MRILUDIR     = /var/tmp/mrilu/
##   Google test library directory
GTEST_LIB    = /var/tmp/lib
##   Google test include directory
GTEST_INC    = /var/tmp/include
##   Project base directory
PROJECT_BASE = /var/tmp/i-emic
##   Make flags
MFLAGS       = -j 4
##   Local
LOCAL_CXX_FLAGS  = -Wall -std=c++11 -O0
##=================================================================
include $(PROJECT_BASE)/make.inc/Makefile.all